apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: myapps
  labels:
    app: code-server
spec:

  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      nodeSelector:
        nodetype: agent
      containers:
        - name: code-server
          image: 192.168.4.30:5000/code-server:latest
          imagePullPolicy: Always
          env:
            - name: DEFAULT_WORKSPACE
              value: /home/devpi/workspace
          volumeMounts:
            - name: code-server-data
              mountPath: /home/devpi
          resources:
            requests:
              cpu: 1500m
              memory: 1.5Gi
          ports:
            - containerPort: 8080
      volumes:
        - name: code-server-data
          persistentVolumeClaim:
            claimName: code-server-pvc