apiVersion: v1
kind: Service
metadata:
  labels:
    app: code-server
  name: code-server
  namespace: myapps
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: code-server
  type: ClusterIP
